#!/bin/bash
# Request 8 gigabytes of real memory (RAM) 2 cores *4G = 8
#SBATCH --mem=8G
# Request 2 cores
#SBATCH --cpus-per-task=2
# Email notifications
#SBATCH --mail-user=gadams3@sheffield.ac.uk
# Email notifications
#SBATCH --mail-type=ALL
# Change job output log file name (default is slurmJOBID)
#SBATCH --output=output.MinimapStringtieSalmonDS2021_281124.out
# Request more time (default is 8 hours)
#SBATCH --time=24:00:00

#Activate the repository
#echo -e "if [[ -e '/usr/local/extras/Genomics' ]];\nthen\n\tsource /usr/local/extras/Genomics/.bashrc\nfi" >> $HOME/.bash_profile
source /usr/local/extras/Genomics/.bashrc

# Set the OPENMP_NUM_THREADS environment variable to 4
# This is needed to ensure efficient core usage.
export OMP_NUM_THREADS=$SLURM_CPUS_PER_TASK

SampleArray=$(cat /fastdata/bop23ga/DietSwitch2_8_2021/samplelist.txt)

for g in ${SampleArray[@]}
do
#Aligment to genome using minimap2
minimap2 -ax splice /shared/simons_lab1/Shared/nanopore_output/Genomes_and_Transcriptomes/Drosophila_melanoganogaster.BDGP6.32.dna.toplevel.fa /fastdata/bop23ga/DietSwitch2_8_2021/fastq_TOUSE/${g}_merge_trimmed.fastq | samtools view -Sb > /fastdata/bop23ga/DietSwitch2_8_2021/MinimapOut/${g}.bam
samtools sort -@ 2 -m 4G -o /fastdata/bop23ga/DietSwitch2_8_2021/MinimapOut/${g}_sorted.bam /fastdata/bop23ga/DietSwitch2_8_2021/MinimapOut/${g}.bam
done

for g in ${SampleArray[@]}
do
#StringTie to assemble transcripts into a transcriptome according to the gene info from the genome
#Merge with StringTie
stringtie -p 2 -B -L -G /shared/simons_lab1/Shared/nanopore_output/Drosophila_melanogaster.BDGP6.32.103.gtf -o /fastdata/bop23ga/DietSwitch2_8_2021/MinimapOut/${g}/${g}_stringtie.gtf /fastdata/bop23ga/DietSwitch2_8_2021/MinimapOut/${g}_sorted.bam
done

for g in ${SampleArray[@]}
do
#Aligment to transcriptome using minimap2 for salmon
minimap2 -ax splice /shared/simons_lab1/Shared/nanopore_output/Genomes_and_Transcriptomes/Drosophila_melanoganogaster.BDGP6.32.cdna.all.fa /fastdata/bop23ga/DietSwitch2_8_2021/fastq_TOUSE/${g}_merge_trimmed.fastq | samtools view -Sb > /fastdata/bop23ga/DietSwitch2_8_2021/MinimapCDNAOut/${g}.bam
done

source /usr/local/community/Genomics/apps/miniconda/etc/profile.d/conda.sh
conda activate /usr/local/community/Genomics/apps/mambaforge/envs/salmon

for g in ${SampleArray[@]}
do
#Get read counts with salmon
salmon quant --ont -t /shared/simons_lab1/Shared/nanopore_output/Genomes_and_Transcriptomes/Drosophila_melanogaster.BDGP6.32.cdna.all.fa -l U -a /fastdata/bop23ga/DietSwitch2_8_2021/MinimapCDNAOutput/${g}.bam -o /fastdata/bop23ga/DietSwitch2_8_2021/SalmonOut/${g}_salmonout/
done
