#!/bin/bash
# Request 8 gigabytes of real memory (RAM) 2 cores *4G = 8
#SBATCH --mem=8G
# Request 2 cores
#SBATCH --cpus-per-task=2
# Email notifications
#SBATCH --mail-user=gadams3@sheffield.ac.uk
# Email notifications if the job fails
#SBATCH --mail-type=ALL
# Change job output log file name (default is slurmJOBID)
#SBATCH --output=output.MinimapStringtieVitC_181024.out
# Request more time (default is 8 hours)
#SBATCH --time=48:00:00
